### ---------------
### MOVIL
### ---------------

GET http://localhost:8888/index.php/movil?patente=GWI322 HTTP/1.1

### 
GET http://localhost:8888/index.php/movil?descripcion=5741 HTTP/1.1

### 
GET http://localhost:8888/index.php/movil?dependencia=05 HTTP/1.1


### ---------------
### GRUPO
### ---------------

### GET
GET http://localhost:8888/index.php/grupo HTTP/1.1

### GET SINGLE
GET http://localhost:8888/index.php/grupo/1 HTTP/1.1

### DELETE
DELETE http://localhost:8888/index.php/grupo/1 HTTP/1.1

### POST
POST http://localhost:8888/index.php/grupo HTTP/1.1
Content-Type: application/json

{
    "grupNombre":"Camionetas",
    "grupDescripcion":"Camionetas Toyota modelo 2016"
}

### PUT
PUT http://localhost:8888/index.php/grupo HTTP/1.1

{
    "grupId": 1,
    "grupNombre": "Camionetas",
    "grupDescripcion": "Camionetas Toyota modelo nuevo"
}

### ---------------
### Tarea
### ---------------

### GET
GET http://localhost:8888/index.php/tarea HTTP/1.1

### POST
POST http://localhost:8888/index.php/tarea HTTP/1.1
Content-Type: application/json

{
    "tareNombre": "Tarea 1",
    "tareDescripcion": "Tarea creada por Matias Suez",
    "tareUnidadMedida": "Litros",
    "tareCantidad": 2,
    "tareCosto": 50
}

### PUT
PUT http://localhost:8888/index.php/tarea HTTP/1.1

{
    "tareId": 6,
    "tareNombre": "Tarea Modificada",
    "tareDescripcion": "Tarea modificada por Matias Suez",
    "tareUnidadMedida": "Metros",
    "tareCantidad": 3,
    "tareCosto": 75
}

### DELETE
DELETE http://localhost:8888/index.php/tarea/6 HTTP/1.1


### ---------------
### Servicios
### ---------------

### POST
POST http://localhost:8888/index.php/servicio HTTP/1.1

{
    "servNombre": "Servicio de prueba",
    "servDescripcion": "Descripcion de prueba",
    "servPeriodo": 183,
    "servKM": 15000,
    "servFecha": 1
}

### PUT
PUT http://localhost:8888/index.php/servicio HTTP/1.1

{
    "servId": 7,
    "servNombre": "Servicio de prueba modificado",
    "servDescripcion": "Descripcion de prueba modificada",
    "servPeriodo": 184,
    "servKM": 15050,
    "servFecha": 0
}

### GET SINGLE
GET http://localhost:8888/index.php/servicio/7 HTTP/1.1

### GET
GET http://localhost:8888/index.php/servicio HTTP/1.1

### DELETE
DELETE http://localhost:8888/index.php/servicio/7 HTTP/1.1

### ---------------
### ServicioTarea
### ---------------

### POST
POST http://localhost:8888/index.php/servicio-tarea HTTP/1.1

{
    "setaServId": 1,
    "setaTareId": 1,
}

### PUT
PUT http://localhost:8888/index.php/servicio-tarea HTTP/1.1

{
    "setaId": 10,
    "setaServId": 4,
    "setaTareId": 2
}

### GET
GET http://localhost:8888/index.php/servicio-tarea HTTP/1.1

### GET SINGLE
GET http://localhost:8888/index.php/servicio-tarea/10 HTTP/1.1

### DELETE
DELETE http://localhost:8888/index.php/servicio-tarea/10 HTTP/1.1
